#ansible_ssh_user: root
#ansible_ssh_pass: i need coffee

kube_node_type: minion

kubernetes_hostname: kube-minion-3

kubernetes_flanneld_config_etcd_endpoints: "http://kube-master:2379"
kubernetes_flanneld_config_etcd_key: "/kube-centos/network"
kubernetes_flanneld_options: ""

kubernetes_kube_config_logtostderr: "true"
kubernetes_kube_config_verbosity: 0
kubernetes_kube_config_allow_priv: "false"
kubernetes_kube_config_kube_master_endpoint: "http://kube-master:8080"
kubernetes_kube_config_etcd_servers: "http://kube-master:2379"

kubernetes_kubelet_config_address: "--address=0.0.0.0"
kubernetes_kubelet_config_port: "--port=10250"
kubernetes_kubelet_config_hostname: "--hostname-override=kube-minion-3"
kubernetes_kubelet_config_apiserver: "--api-servers=http://kube-master:8080"
kubernetes_kubelet_config_podinfra: "--pod-infra-container-image=gcr.io/google_containers/pause:latest"
kubernetes_kubelet_args: ""
