---
- name: Add ansible repository from PPA
  become: yes
  apt_repository:
    repo: 'ppa:ansible/ansible'

- name: Install ansible
  become: yes
  apt:
    name: ansible
    state: latest
    update_cache: yes
    force: yes

- name: Turning off Host Key Checking
  replace:
    dest: /etc/ansible/ansible.cfg
    regexp: '#host_key_checking'
    replace: 'host_key_checking'
  become: true


